<?php
namespace  Api\Controller;
use Think\Controller\RestController;
class IndexBaseController extends RestController {
   

       protected function response($data, $message='',$code = 200,$type="json")
       {
           parent::response(['message'=>$message,'data'=>$data], $type, $code); // TODO: Change the autogenerated stub
       }
}